# Generated by Django 4.0.1 on 2022-03-06 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='publisher',
            old_name='webstie',
            new_name='website',
        ),
    ]
